extends Node

## GameState — single source of truth for the player's resources.
##
## Holds cash and the tracked materials. Nothing else in the game should
## read or write these values directly with raw assignment. Instead, go
## through the methods below, which update the value AND announce the
## change on the EventBus. That way any component (UI, market, etc.) can
## react without GameState ever needing to know they exist.
##
## Session 1 scope: storage + change notifications only. No gameplay,
## no economy, no decisions live here.

# --- Starting values ---
const STARTING_CASH: int = 10000

# --- State ---
var company_name: String = ""
var cash: int = STARTING_CASH
var coal: int = 0
var limestone: int = 0
var salt: int = 0
var crush: int = 0
var blocks: int = 0

# Block-making materials (sourced/bought in later sessions; consumed by the
# block factory).
var cement: int = 0
var sand: int = 0
var water: int = 0

# Farming (Mega-build): harvested produce + farm inputs.
var wheat: int = 0
var rice: int = 0
var cotton: int = 0
var sugarcane: int = 0
var seeds: int = 0
var fertilizer: int = 0

# Steel chain (Mega-build).
var iron_ore: int = 0
var steel: int = 0

# Military production (Mega-build).
var weapons: int = 0
var ammo: int = 0

# Power & fuel (Mega-build). Power is banked units generated by gensets /
# solar and drawn down by factories (a live grid model is a later slice).
var fuel: int = 0
var power: int = 0

## Graded crush, sorted by the grizzly. grade label (e.g. "20mm", "dust")
## -> amount. Kept as a dictionary so new grades can appear without
## bloating the fixed resource list above.
var crush_grades: Dictionary = {}


func _ready() -> void:
	# Announce initial values once everything is loaded, so any listener
	# that connects at startup can sync its display immediately.
	EventBus.cash_changed.emit(cash)
	EventBus.resource_changed.emit("coal", coal)
	EventBus.resource_changed.emit("limestone", limestone)
	EventBus.resource_changed.emit("salt", salt)
	EventBus.resource_changed.emit("crush", crush)
	EventBus.resource_changed.emit("blocks", blocks)
	EventBus.resource_changed.emit("cement", cement)
	EventBus.resource_changed.emit("sand", sand)
	EventBus.resource_changed.emit("water", water)
	EventBus.resource_changed.emit("wheat", wheat)
	EventBus.resource_changed.emit("rice", rice)
	EventBus.resource_changed.emit("cotton", cotton)
	EventBus.resource_changed.emit("sugarcane", sugarcane)
	EventBus.resource_changed.emit("seeds", seeds)
	EventBus.resource_changed.emit("fertilizer", fertilizer)
	EventBus.resource_changed.emit("iron_ore", iron_ore)
	EventBus.resource_changed.emit("steel", steel)
	EventBus.resource_changed.emit("weapons", weapons)
	EventBus.resource_changed.emit("ammo", ammo)
	EventBus.resource_changed.emit("fuel", fuel)
	EventBus.resource_changed.emit("power", power)


# --- Company lifecycle ---

## Start a new company with the given name. Stores the name and announces
## it on the EventBus. Cash already starts at STARTING_CASH.
func start_company(name: String) -> void:
	company_name = name
	EventBus.company_started.emit(company_name)


# --- Cash ---

## Add cash (e.g. from a sale). Use a positive amount.
func add_cash(amount: int) -> void:
	if amount <= 0:
		return
	cash += amount
	EventBus.cash_changed.emit(cash)


## Try to spend cash. Returns true if the player could afford it (and the
## cash was deducted), false if not enough (nothing is deducted).
func spend_cash(amount: int) -> bool:
	if amount <= 0:
		return true
	if cash < amount:
		return false
	cash -= amount
	EventBus.cash_changed.emit(cash)
	return true


# --- Resources ---

## Returns the current amount of a tracked resource, or 0 if the name is
## not recognised.
func get_resource(resource_name: String) -> int:
	match resource_name:
		"coal": return coal
		"limestone": return limestone
		"salt": return salt
		"crush": return crush
		"blocks": return blocks
		"cement": return cement
		"sand": return sand
		"water": return water
		"wheat": return wheat
		"rice": return rice
		"cotton": return cotton
		"sugarcane": return sugarcane
		"seeds": return seeds
		"fertilizer": return fertilizer
		"iron_ore": return iron_ore
		"steel": return steel
		"weapons": return weapons
		"ammo": return ammo
		"fuel": return fuel
		"power": return power
		_:
			push_warning("GameState.get_resource: unknown resource '%s'" % resource_name)
			return 0


## Add to a tracked resource. Use a positive amount.
func add_resource(resource_name: String, amount: int) -> void:
	if amount <= 0:
		return
	if not _set_resource(resource_name, get_resource(resource_name) + amount):
		return
	EventBus.resource_changed.emit(resource_name, get_resource(resource_name))


## Try to remove from a tracked resource. Returns true if there was enough
## (and it was removed), false otherwise (nothing is removed).
func remove_resource(resource_name: String, amount: int) -> bool:
	if amount <= 0:
		return true
	var current: int = get_resource(resource_name)
	if current < amount:
		return false
	if not _set_resource(resource_name, current - amount):
		return false
	EventBus.resource_changed.emit(resource_name, get_resource(resource_name))
	return true


# --- Crush grades (Session 9) ---

## Current amount of a given crush grade (0 if that grade has none yet).
func get_crush_grade(grade: String) -> int:
	return int(crush_grades.get(grade, 0))


## Add to a crush grade's tally and announce it. Use a positive amount.
func add_crush_grade(grade: String, amount: int) -> void:
	if amount <= 0:
		return
	crush_grades[grade] = get_crush_grade(grade) + amount
	EventBus.crush_grade_changed.emit(grade, crush_grades[grade])


# --- Internal ---

## Writes a resource value by name. Returns false if the name is unknown.
func _set_resource(resource_name: String, value: int) -> bool:
	match resource_name:
		"coal": coal = value
		"limestone": limestone = value
		"salt": salt = value
		"crush": crush = value
		"blocks": blocks = value
		"cement": cement = value
		"sand": sand = value
		"water": water = value
		"wheat": wheat = value
		"rice": rice = value
		"cotton": cotton = value
		"sugarcane": sugarcane = value
		"seeds": seeds = value
		"fertilizer": fertilizer = value
		"iron_ore": iron_ore = value
		"steel": steel = value
		"weapons": weapons = value
		"ammo": ammo = value
		"fuel": fuel = value
		"power": power = value
		_:
			push_warning("GameState._set_resource: unknown resource '%s'" % resource_name)
			return false
	return true
